services:
  monitor:
    build: .
    restart: unless-stopped
    tty: true
    stdin_open: true
    cap_add:
      - NET_RAW
    volumes:
      - ./config.json:/app/config.json
      - ./logs:/app/logs
    network_mode: host
